const https = require('https');

const CF = 'https://www.curseforge.com/minecraft/mc-mods/';
const MR = 'https://modrinth.com/mod/';

const MODS = [
['The Aether',CF+'the-aether'],
['Biomes O Plenty',CF+'biomes-o-plenty'],
['Oh The Biomes Weve Gone',CF+'oh-the-biomes-weve-gone'],
['Regions Unexplored',CF+'regions-unexplored'],
['Geophilic',MR+'geophilic'],
['Geofisica',CF+'geofisica'],
['Geolosy',CF+'geolosy'],
['Additions to Modded Biomes',CF+'additions-to-modded-biomes'],
['Aeroblender',CF+'aeroblender'],
['Dynamic Trees',CF+'dynamictrees'],
['DT BiomesOPlenty',CF+'dtbop'],
['Climate Rules',CF+'climaterules'],
['YUNG Cave Biomes',CF+'yungs-cave-biomes'],
['Distant Horizons',MR+'distanthorizons'],
['Dungeons and Taverns',CF+'dungeons-and-taverns'],
['Repurposed Structures',CF+'repurposed-structures-forge'],
['Towns and Towers',CF+'towns-and-towers'],
['Additional Structures',CF+'additional-structures'],
['Oh The Structures',CF+'oh-the-structures-youll-go'],
['Moog Structures',CF+'moog-structures'],
['Moog End',CF+'moogis-end-structures'],
['Moog Nether',CF+'moogis-nether-structures'],
['Moog Ocean',CF+'moogis-ocean-structures'],
['Moog Villages',CF+'moogis-villages'],
['Watchtowers',CF+'watchtowers'],
['Abandoned Watchtowers',CF+'abandoned-watchtowers'],
['Ancient Ruins',CF+'ancient-ruins'],
['Medieval Buildings',CF+'medieval-buildings'],
['Medieval Buildings E1',CF+'medieval-buildings-edition-1'],
['Sky Villages',CF+'sky-villages'],
['Old Villages',CF+'old-villages'],
['Villages Plus',CF+'villages-plus'],
['Village More',CF+'village-more'],
['Villager Gardens',CF+'villager-gardens'],
['Ruined Buildings',CF+'ruined-buildings'],
['Simply Houses',CF+'simply-houses'],
['Structure Essential',CF+'structure-essential'],
['Structures Towers',CF+'structures-towers'],
['Create Structures',CF+'create-structures'],
['Underwater Ruins',CF+'hope-better-underwater-ruins'],
['Living Space',CF+'livingspace'],
['Kurtis Interiors',CF+'kurtis-interiors'],
['Universal Bonus Chest',CF+'universal-bonus-chest'],
['YUNG Better Caves',CF+'yungs-better-caves'],
['YUNG Desert Temples',CF+'yungs-better-desert-temples'],
['YUNG Better Dungeons',CF+'yungs-better-dungeons'],
['YUNG Jungle Temples',CF+'yungs-better-jungle-temples'],
['YUNG Mineshafts',CF+'yungs-better-mineshafts'],
['YUNG Nether Fortresses',CF+'yungs-better-nether-fortresses'],
['YUNG Ocean Monuments',CF+'yungs-better-ocean-monuments'],
['YUNG Strongholds',CF+'yungs-better-strongholds'],
['YUNG Witch Huts',CF+'yungs-better-witch-huts'],
['YUNG Extras',CF+'yungs-extras'],
['Alex Mobs',CF+'alexs-mobs'],
['Mowzie Mobs',CF+'mowzies-mobs'],
['Naturalist',CF+'naturalist'],
['Friends and Foes',CF+'friends-and-foes'],
['Mutant Monsters',CF+'mutant-monsters'],
['More Golems',CF+'more-golems'],
['Creeper Overhaul',CF+'creeper-overhaul'],
['More Sniffers',CF+'more-sniffers'],
['More Villagers',CF+'more-villagers'],
['Guard Villagers',CF+'guard-villagers'],
['Little Blue Demon',CF+'little-blue-demon'],
['Horror Element',CF+'horror-element-mod'],
['Aquamirae',CF+'aquamirae'],
['Darker Depths',CF+'darker-depths'],
['Dragon Flight',CF+'dragonflight'],
['More Drago',CF+'moredrago'],
['Toy Soldiers',CF+'toy-soldiers'],
['Companion',CF+'companion'],
['Illagers Wear',CF+'illagers-wear'],
['Farmers Delight',CF+'farmers-delight'],
['Farmers Knives',CF+'farmers-knives'],
['Farmers Resplendent',CF+'farmers-resplendent'],
['Barbeques Delight',CF+'barbeques-delight'],
['Brewin Chewin',CF+'brewin-and-chewin'],
['Allocave Delight',CF+'allocave-delight'],
['Crabbers Delight',CF+'crabbers-delight'],
['Delightful',CF+'delightful'],
['Enders Delight',CF+'enders-delight'],
['Engineers Delight',CF+'engineers-delight'],
['Fruits Delight',CF+'fruitsdelight'],
['Miners Delight',CF+'miners-delight'],
['My Nether Delight',CF+'my-nether-delight'],
['Oceanic Delight',CF+'oceanic-delight'],
['Twilight Delight',CF+'twilight-delight'],
['TF Dungeons Villages',CF+'twilightforest-dungeons-and-villages'],
['When Dungeons Arise',CF+'when-dungeons-arise'],
['Dungeons Delight',CF+'dungeons-delight'],
['Loot Integrations WDA',CF+'loot-integrations-when-dungeons-arise'],
['RunicLib',CF+'runiclib'],
['Connoisseurs Delight',CF+'connoisseurs-delight'],
['Irons Spells Delight',CF+'irons-spells-delight'],
['Cuisines',CF+'cuisines'],
['Aquaculture',CF+'aquaculture-2'],
['Stardew Fishing',CF+'stardew-fishing'],
['Farms and Furnitures',CF+'farms-and-furnitures'],
['DoN Brewery',CF+'don-brewery'],
['Create',CF+'create'],
['Create Addition',CF+'createaddition'],
['Create Aquatic',CF+'create-aquatic-ambition'],
['Create Connected',CF+'create-connected'],
['Create Recycling',CF+'create-recycling'],
['Create Things',CF+'create-things-and-misc'],
['Create Aeronautics',CF+'create-aeronautics'],
['Create Better',CF+'createbetter'],
['Create Big Cannons',CF+'create-big-cannons'],
['Create Confectionery',CF+'create-confectionery'],
['Create Deco',CF+'create-deco'],
['Create Generators',CF+'create-generators'],
['Create Cavation',CF+'create-cavation'],
['Iron Spellbooks',CF+'irons-spells-n-spellbooks'],
['Better Combat',MR+'better-combat'],
['Simply Swords',CF+'simply-swords'],
['Artifacts',CF+'artifacts'],
['Epic Knights',CF+'epic-knights-shields-and-armor'],
['Immersive Armors',MR+'immersive-armors'],
['Fantasy Armor',CF+'fantasy-armor'],
['Cataclysm',CF+'cataclysm-mod'],
['L Ender Cataclysm',CF+'l-enders-cataclysm'],
['Hellish Tridents',CF+'hellish-tridents'],
['Ranged Weapons',CF+'ranged-weapons'],
['Armored Redstone',CF+'armored-redstone'],
['Dawn of it',CF+'dawnofit'],
['Accessories',MR+'accessories'],
['Backpacked',CF+'backpacked'],
['Cosmetic Armor',CF+'cosmetic-armor-reworked'],
['Spell Engine',MR+'spell-engine'],
['Spell Power',MR+'spell-power'],
['Immersive Engineering',CF+'immersive-engineering'],
['Paxii',CF+'paxii'],
['Royal Variants',CF+'royal-variants'],
['Macaw Bridges',CF+'macaws-bridges'],
['Macaw Doors',CF+'macaws-doors'],
['Macaw Furniture',CF+'macaws-furniture'],
['Macaw Lights',CF+'macaws-lights-and-lamps'],
['Macaw Paintings',CF+'macaws-paintings'],
['Macaw Paths',CF+'macaws-paths-and-pavings'],
['Macaw Roofs',CF+'macaws-roofs'],
['Macaw Fences',CF+'macaws-fences-and-walls'],
['Macaw Windows',CF+'macaws-windows'],
['Macaw BYG',CF+'mcw-byg'],
['Macaw Biomes',CF+'mcwbiomesushi'],
['Another Furniture',MR+'anotherfurniture'],
['MrCrayfish Furniture',CF+'mrcrayfishs-furniture-mod'],
['Supplementaries',CF+'supplementaries'],
['Refurbished Furniture',CF+'refurbished-furniture'],
['Design Decor',CF+'design-n-decor'],
['Rustic',CF+'rustic'],
['Display Case',CF+'display-case'],
['Variant Chests',CF+'variant-chests'],
['Copycats',MR+'copycats'],
['Paintings',MR+'paintings'],
['Quark',CF+'quark'],
['Prickle',CF+'prickle'],
['Chimes',CF+'chimes'],
['DoN Lanterns',CF+'don-lanterns'],
['Subtle Effects',CF+'subtle-effects'],
['Ecologics',CF+'ecologics'],
['Fusion',CF+'fusion-connected-textures'],
['Sodium',MR+'sodium'],
['FerriteCore',MR+'ferrite-core'],
['ModernFix',CF+'modernfix'],
['Chunky',MR+'chunky'],
['Entity Culling',MR+'entityculling'],
['Saturn',MR+'saturn'],
['Krypton',MR+'krypton'],
['Oculus',CF+'oculus'],
['Spark',MR+'spark'],
['AI Improvements',CF+'ai-improvements'],
['Let Me Despawn',MR+'let-me-despawn'],
['Jade',CF+'jade'],
['JEI',CF+'jei'],
['AppleSkin',CF+'appleskin'],
['Xaero Minimap',CF+'xaeros-minimap'],
['Xaero World Map',CF+'xaeros-world-map'],
['Mouse Tweaks',CF+'mouse-tweaks'],
['InvMove',CF+'invmove'],
['Clumps',CF+'clumps'],
['Enchantment Descriptions',CF+'enchantment-descriptions'],
['Camera Overhaul',MR+'cameraoverhaul'],
['Camera Utils',CF+'camera-utils'],
['Better Third Person',CF+'better-third-person'],
['Enhanced Boss Bars',CF+'enhanced-boss-bars'],
['Resourcify',CF+'resourcify'],
['Entity Model Features',MR+'entity-model-features'],
['Entity Texture Features',MR+'entitytexturefeatures'],
['Forgematica',CF+'forgematica'],
['CMDCam',CF+'cmdcam'],
['Simple Voice Chat',CF+'simple-voice-chat'],
['WorldEdit',CF+'worldedit'],
['Transparent',CF+'transparent'],
['More Leash',MR+'moreleash'],
['Better Archeology',CF+'better-archeology'],
['Sound Physics',CF+'sound-physics-remastered'],
['Diagonal Fences',MR+'diagonal-fences'],
['Block Faster',CF+'block-faster-bypasser'],
['Packet Fixer',CF+'packet-fixer'],
['LambDynamicLights',MR+'lambdynamiclights'],
['Nether Portal Fix',CF+'netherportalfix'],
['More Mob Griefing',CF+'more-mob-griefing-options'],
['Tombstone',CF+'tombstone'],
['Easy NPC',CF+'easy-npc'],
['Architectury',MR+'architectury-api'],
['GeckoLib',CF+'geckolib'],
['Bookshelf',CF+'bookshelf'],
['Balm',CF+'balm'],
['Citadel',CF+'citadel'],
['Cloth Config',CF+'cloth-config'],
['Collective',CF+'collective'],
['Puzzles Lib',CF+'puzzles-lib'],
['Iceberg',CF+'iceberg'],
['Moonlight Lib',CF+'moonlight-lib'],
['Zeta',CF+'zeta'],
['GlitchCore',CF+'glitchcore'],
['Cristellib',CF+'cristellib'],
['Lodestone',CF+'lodestone'],
['Structure Gel API',CF+'structure-gel-api'],
['YUNG API',CF+'yungs-api'],
['Cupboard',CF+'cupboard'],
['Forgified Fabric',CF+'forgified-fabric-api'],
['Konkrete',CF+'konkrete'],
['Framework',CF+'framework'],
['Ash API',CF+'ash-api'],
['AttributeFix',CF+'attributefix'],
['Integrated API',CF+'integrated-api'],
['Cyclops Core',CF+'cyclopscore'],
['AzureLib Armor',CF+'azurelib-armor'],
['Player Animation',MR+'player-animation-lib'],
['Mysterious Mountain Lib',CF+'mysterious-mountain-lib'],
['More RPG Library',CF+'more-rpg-library'],
['YACL',MR+'yacl'],
['Excavated Variants',MR+'excavated-variants'],
['Loot Integrations',CF+'lootinteg'],
['MAFGLI',CF+'mafgli'],
['Fuzzy Crafting',MR+'fuzzy-crafting'],
['Just Hammers',CF+'just-hammers'],
['Just Ores',CF+'just-ores'],
['Lettuce Mod',CF+'lettuce-mod'],
['TermBand',CF+'termband'],
['JLine',CF+'jline'],
];

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

function check(name, url) {
  return new Promise(resolve => {
    const opts = { headers: { 'User-Agent': UA, 'Accept': 'text/html,application/xhtml+xml' }, timeout: 10000 };
    const req = https.get(url, opts, res => {
      res.resume();
      resolve({ name, url, status: res.statusCode });
    });
    req.on('error', e => resolve({ name, url, status: 'ERR:' + e.code }));
    req.on('timeout', () => { req.destroy(); resolve({ name, url, status: 'TIMEOUT' }); });
  });
}

async function run() {
  const results = [];
  for (const [name, url] of MODS) {
    const r = await check(name, url);
    process.stdout.write(r.status + ' ' + name + '\n');
    results.push(r);
    await sleep(150);
  }

  const found404 = results.filter(r => r.status === 404);
  console.log('\n=============================');
  console.log('LIENS MORTS (404) :');
  if (found404.length === 0) console.log('  Aucun !');
  found404.forEach(r => console.log('  ' + r.name + '\n    ' + r.url));
  console.log('Total verifie: ' + results.length + ' | 404: ' + found404.length);
}

run();
